#!/bin/sh
homeDir=`su -c "eval echo ~$USER" -s /bin/sh klanc`
su -c "cat $homeDir/.dotfiles/configs/i3.conf > $homeDir/.config/i3/config" -s /bin/sh klanc
su -c "cat $homeDir/.dotfiles/sensitive/i3extra.conf >> $homeDir/.config/i3/config" -s /bin/sh klanc
